version: '3'
services:
  main:
    image: main
    build: . 
    command: /bin/sh -c "rm -f /products/tmp/pids/server.pid && bundle exec rails s -p 3300 -b '0.0.0.0'"
    volumes:
      - .:/products
    ports:
      - "3300:3300"
    depends_on:
      - db

  db:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_vol:/var/lib/mysql

volumes:
  mysql_vol:
